language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.22"
  - "5.26"
  - "5.28"
  - "5.30"
sudo: false
#install:
#  - "source ./setup.sh"
#script: "dzil test --verbose"
before_install:
  - perlbrew list
  - "perlbrew exec --with $stableperl 'cpanm --quiet --notest Dist::Zilla'"
  - "perlbrew exec --with $stableperl 'dzil authordeps | cpanm --quiet --notest'"
  - "perlbrew exec --with $stableperl 'dzil build --in $builddir'"
install:
  - '(cd $builddir && cpanm --quiet --notest --installdeps .)'
  # extra deps for author tests:
  - cpanm --quiet --notest Test::Perl::Critic Test::Pod
script:
  - '(cd $builddir && prove -lr t)'
