---
abstract: 'A simple module to parse FASTA and FASTQ files, supporting compressed files and paired-ends.'
author:
  - 'Andrea Telatin <andrea@telatin.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FASTX-Reader
provides:
  FASTX::PE:
    file: lib/FASTX/PE.pm
    version: v1.0.1
  FASTX::Reader:
    file: lib/FASTX/Reader.pm
    version: v1.0.1
  FASTX::ScriptHelper:
    file: lib/FASTX/ScriptHelper.pm
    version: v1.0.1
recommends:
  File::Which: '0'
requires:
  Capture::Tiny: '0.40'
  Carp: '1.2'
  Data::Dumper: '2.1'
  File::Fetch: '0'
  FindBin: '1.3'
  Time::HiRes: '0'
  perl: '5.012'
resources:
  repository: https://github.com/telatin/FASTQ-Parser
version: 1.0.1
x_generated_by_perl: v5.18.2
x_serialization_backend: 'YAML::Tiny version 1.73'
